language: python
python:
  - "2.6"
  - "2.7"
install:
  # New aludel still lives in a branch, so get it from there.
  - "pip install -e 'git+https://github.com/praekelt/aludel.git@feature/issue-7-PrefixedTableCollection-metadata#egg=aludel'"
  - "pip install -r requirements.txt"
  - "pip install -r test-requirements.txt"
  - "pip install coveralls"
script:
  - py.test --cov=airtime_service airtime_service
after_success:
  - coveralls
